version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
  nest-template:
    build: .
    environment:
      - APP_PORT=3000
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=h3it
      - JWT_EXPIRESIN=300s
    depends_on:
      - mongo
    ports:
      - "3005:3000"